### PR TITLE
add deps.ts reference to subcommand intro

### PR DESCRIPTION
**Pull request by mwcz**
related to #95

## Summary

* links to the deps.ts creation docs from the subcommand intro

## Other Notes

I missed this when following the single-command intro and was confused about where deps.ts was supposed to come from.  Maybe this could help others too.

### CODE REVIEW

**Comment by mwcz** [comment]
I understand.  As I was reading the single-command and sub-command tutorials, there's no indication that any prior steps need to be completed.  I made sure to check the "Before you begin" sections in each tutorial and there were no prerequisites listed.

It's been over a week since I read the "Add Line as a Dependency" page, so the memory of it saying "Before you get started with any tutorial..." was long gone.  That's the entry-point I was coming from.

**Comment by crookse** [comment]
probably an area we should improve but we didn't add references to the add {module} as a dependency page because it was too much copy paste for each of our modules for each page that needs it. however adding that link to each page could improve UX.

**Comment by mwcz** [comment]
Yeah, I definitely understand not wanting to clutter up the docs like this.  I think in my particular case, if the "Add Line as a Dependency" had been named "Initial setup" or was under a category by that name, I would have found it immediately.  Or if "deps.ts" were somewhere in the title.  Anyway, I'm sure there's a cleaner way to solve this, so feel free to close these PRs.

**Comment by crookse** [comment]
made a comment regarding this: https://github.com/drashland/website-v2/pull/95#issuecomment-1094036578

**Comment by crookse** [comment]
This will be closed by https://github.com/drashland/website-v2/issues/144

**Pull request closed without merging**
