### PR TITLE
docs(vital/v1.x): Add initial v1 documentation

### PR DESCRIPTION
**Pull request by ebebbington**

### CODE REVIEW

**Comment by ebebbington** [comment]
atm, some pages dont display anything

**Review by Guergeiro — APPROVED** [review]

**Comment by crookse** [comment]
LGTM, but do we plan to deploy these pages without content?

**Comment by ebebbington** [comment]
@crookse so I was checking local and other module docs in that deployment and they have the same problem, some pages just don’t have content, but I checked prod and they are all fine, so I think it’s just these or deployments that are a bit buggy, but in prod they should be fine?

**Comment by crookse** [comment]
oh wtf.

**Pull request merged**
