### PR TITLE
docs(drash/v2.x): Add documentation for using prefixes

### PR DESCRIPTION
**Pull request by ebebbington**
Adds docs on how to use prefixes

### CODE REVIEW

**Comment by Guergeiro** [comment]
Something is wrong with the preview. Is it only me?

**Comment by ebebbington** [comment]
It’s fine for me?

**Comment by Guergeiro** [comment]
> It’s fine for me?

image

Can you confirm?

**Comment by ebebbington** [comment]
Ah ok I see what you mean

**Review by crookse — APPROVED** [review]

**Comment by crookse** [comment]
my bad @Guergeiro. i fixed it in 9658052. page is deployed: https://drash.land/drash/v2.x/tutorials/resources/prefixing-paths

**Pull request merged**
