### PR TITLE
chore: Add ci; fmt & lint

### LINKED ISSUE #4: Chore - Clean up code
## Summary

What: Code was done fairly quickly to roll out Drash v2.x docs. It hasn't been linted, hasn't been formatted, and hasn't been checked against best practices. The code needs to formatted, linted, and checked against best practices in React AND Next.js.

Also, let's have a GitHub workflow that lints and does a formatting check.

Why: Let's not have crappy code and make it easier to follow a standard.

## Acceptance Criteria

Below is a list of tasks that must be completed before this issue can be closed.

- [ ] Code is linted
- [ ] Code is formatted
- [ ] Code follows best practices in React and Next.js
- [ ] GitHub workflow is added to check linting and formatting

### PR DESCRIPTION
**Pull request by ebebbington**
fixes #4

### CODE REVIEW

**Comment by crookse** [comment]
drash intro still has a busted code block. maybe we don't go with `deno fmt` for markdown files?

**Comment by ebebbington** [comment]
@crookse i've fixed it all and gone over the docs multiple times, all is looking good to me now

**Comment by ebebbington** [comment]
💣

**Comment by crookse** [comment]
weird... it works in my local... gonna rerun the workflow

**Pull request merged**
