### PR TITLE
feat(rhum/v2.x): Add documentation

### PR DESCRIPTION
**Pull request by ebebbington**

### CODE REVIEW

**Comment by ebebbington** [comment]
Pretty much just copied everything from v1's doc pages

**Comment by crookse-carimus** [comment]
PR revisions up at #132

**Comment by crookse-carimus** [comment]
I think we should change the `Rhum.stubbed` API to `Rhum.stub`. not sure why we (most likely me) went with `Rhum.stubbed`.

**Review by Guergeiro — APPROVED** [review]
THANK YOU!

**Review by crookse — APPROVED** [review]

**Pull request merged**
